/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-09-14 21:00:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class survey_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Survey</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"survey.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2 align=\"center\"><em>Student Survey</em></h2>\r\n");
      out.write("\r\n");
      out.write("<form name=\"survey_form\" method=\"post\" action=\"surveyProcessing\" onsubmit=\"return dataCheck(this)\">\r\n");
      out.write("  <table align=\"center\" style=\"width: 600px\">\r\n");
      out.write("    <colgroup><col align=\"right\"></col><col align=\"left\"></col></colgroup>\r\n");
      out.write("    <tr><th align=\"right\">Last Name</th><td><input type=\"text\" name=\"tf_lastName\"/></td></tr>\r\n");
      out.write("    <tr><th align=\"right\">First Name</th><td><input type=\"text\" name=\"tf_firstName\"/></td></tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th align=\"right\">Undergraduate Discipline</th>\r\n");
      out.write("      <td><select name=\"cbo_discipline\">\r\n");
      out.write("            <option>Please select a discipline</option>\r\n");
      out.write("        \t\t<option>Art</option>\r\n");
      out.write("        \t\t<option>Business</option>\r\n");
      out.write("        \t\t<option>Education</option>\r\n");
      out.write("        \t\t<option>Engineering</option>\r\n");
      out.write("        \t\t<option>Health Care</option>\r\n");
      out.write("        \t\t<option>Science</option>\r\n");
      out.write("        \t\t<option>Other</option>\r\n");
      out.write("          </select>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr><th align=\"right\">Message</th>\r\n");
      out.write("        <td><textarea name=\"ta_message\" cols=\"40\" rows=\"5\"></textarea></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td/>\r\n");
      out.write("      <td>\r\n");
      out.write("        <input type=\"submit\" value=\"Submit\"/>&nbsp;&nbsp;\r\n");
      out.write("        <input type=\"reset\" value=\"Cancel\"/>     \r\n");
      out.write("\t    </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  <br/>\r\n");
      out.write("</form>\r\n");
      out.write("<p/>\r\n");
      out.write("\r\n");

   // Find absolute URL for the Web application root 
   // so this Web application will work even if it may be deployed at different URLs/ports
   String absoluteURL = javax.servlet.http.HttpUtils.getRequestURL(request).toString();
   absoluteURL = absoluteURL.substring(0, absoluteURL.lastIndexOf('/'));

      out.write("\r\n");
      out.write("<div align=\"center\"><a href=\"");
      out.print(absoluteURL);
      out.write("/query\">Search Survey Records</a></div>\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" align=\"center\" width=\"80%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
  String message = request.getParameter("message");
    String color = request.getParameter("color");
    if (color == null) color = "red";
    if (message != null) {

      out.write("\r\n");
      out.write("       <p align=\"center\"><font color=\"");
      out.print(color);
      out.write('"');
      out.write('>');
      out.print(message);
      out.write("</font></p>\r\n");

    }

      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
